maintainer: Petr Hracek <phracek@redhat.com>

expose: 11211

description:  Memcached is High Performance, Distributed Memory Object Cache.

envvars:
  name: memcached
  version: 0
  release: 1
  arch: x86_64
